version: "3.9"
services:
  elasticsearch:
    image: elastic/elasticsearch:8.6.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
  kibana:
    image: kibana:8.6.1
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch
  redis:
    image: redis:7.0.8
    ports:
      - target: 6379
        published: 6379
  redisbeat:
    image: docker.elastic.co/beats/filebeat:8.6.1
    volumes:
      - ./redisbeats.yml:/usr/share/filebeat/filebeat.yml:ro
    depends_on:
      - elasticsearch
volumes:
  esdata:
    driver: local